# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, aeson, aesonQq, base16Bytestring, base64Bytestring, bcrypt
, blazeBuilder, blazeHtml, byteable, caseInsensitive, cipherAes
, clientsession, cookie, cprngAes, cryptohash, cryptoPubkey
, cryptoRandom, dataDefaultGenerics, deepseq, either, errors, hspec
, httpConduit, httpTypes, HUnit, joseJwt, monadLogger, mtl, network
, networkUri, persistent, persistentSqlite, persistentTemplate
, QuickCheck, scotty, stm, text, time, transformers
, unorderedContainers, uuid, wai, waiExtra
}:

cabal.mkDerivation (self: {
  pname = "broch";
  version = "0.1";
  src = ./.;
  buildDepends = [
    aeson base16Bytestring base64Bytestring bcrypt blazeBuilder
    blazeHtml byteable cipherAes clientsession cookie cprngAes
    cryptohash cryptoPubkey cryptoRandom dataDefaultGenerics errors
    httpConduit httpTypes joseJwt monadLogger mtl persistent
    persistentTemplate scotty stm text time transformers
    unorderedContainers uuid wai
  ];
  testDepends = [
    aeson aesonQq base64Bytestring blazeBuilder caseInsensitive
    cipherAes cookie cprngAes cryptohash cryptoPubkey cryptoRandom
    deepseq either hspec httpTypes HUnit joseJwt mtl network networkUri
    persistent persistentSqlite QuickCheck text time transformers wai
    waiExtra
  ];
  meta = {
    description = "OAuth2/OpenID Connect Server";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
